### ISSUE TITLE
Differences between OrderedDict and CSV row records

### ISSUE THREAD

**Issue by michaeldavie** [domainaware/parsedmarc#101]
I was wondering why some fields are included in the OrderedDict of a parsed record, but not in the CSV version. For example, `dmarc_alignment` is not included in the CSV, and the `spf_alignment` and `dkim_alignment` values in the CSV are based on the `policy_evaluated` values rather than the `alignment` ones, which are left out.

Why is this, and we losing any information by not including the separate `policy_evaluated` and `alignment` fields in the CSV? Are any there scenarios where these values could be different from each other, or are they always the same?

**Comment by seanthegeek** [comment]
The `policy_evaluated` values are the raw values from the aggregate report XML (i.e. `pass` or `fail`) element of the same name. The `alignment` section in the JSON are booleans values I added based on the values of `policy_evaluated` for convenience. 

```python
spf_aligned = policy_evaluated["spf"] == "pass"
dkim_aligned = policy_evaluated["dkim"] == "pass"
dmarc_aligned = spf_aligned or dkim_aligned
new_record["alignment"] = dict()
new_record["alignment"]["spf"] = spf_aligned
new_record["alignment"]["dkim"] = dkim_aligned
new_record["alignment"]["dmarc"] = dmarc_aligned
```

My earliest DMARC parser just took the values from the XML and dumped them to a bulk CSV format. I haven't touched the format since I usually work with JSON.

Sorry for the confusion.
