### ISSUE TITLE
installing parsemarc ver 6.7.4  (error 401 requesting GeoLite2-Country)

### ISSUE THREAD

**Issue by joanjuventench** [domainaware/parsedmarc#139]
Received an unexpected HTTP status code of 401 from https://updates.maxmind.com/app/update_secure?db_md5=00000000000000000000000000000000&challenge_md5=b89718d73302b8313746bece304ad016&user_id=0&edition_id=GeoLite2-Country:
Invalid account ID

And the installation crashes.
Could you please help, with this?

Thank you,

**Comment by seanthegeek** [comment]
Hi. 

MaxMind now requires users to register for a free account in order to download their GeoLite2 databases. Instead of reinventing the wheel, I decided to provide documentation on how to use MaxMind's `geoipupdate` tool, rather than trying to build that function into parsedmarc.

https://domainaware.github.io/parsedmarc/#geoipupdate-setup

I just released `parsedmarc` 6.8.0, which removes the code that tries to download the MaxMind database.

After setting up `geoipupdate`, you can upgrade `parsedmarc` by running

```bash
sudo -H pip install -U parsedmarc
```

Let me know if you have any questions.

**Comment by joanjuventench** [comment]
@seanthegeek 
Thank you for info and for taking your time answering.
I made a workaround modifying the utils.py and downloading the mmdb Geolite2  needed file.
I will try this new version 6.8.0

Kind regards,
