### ISSUE TITLE
DMARC Forensic Samples 

### ISSUE THREAD

**Issue by xennn** [domainaware/parsedmarc#19]
Dashboard/DMARC Forensic Samples 

Could not locate that index-pattern-field (id: sample.reply_to.address.keyword)
Could not locate that index-pattern-field (id: source_country.keyword)
Could not locate that index-pattern-field (id: source_reverse_dns.keyword)
Could not locate that index-pattern-field (id: source_country.keyword)

If you need a Sample Forensic Report you can get one from me

**Comment by seanthegeek** [comment]
Hmm. My guess is that you are seeing these because all of the forensic samples you have stored so far don't have

- A reply to header
- A reverse DNS domain for the source IP address
- An identifiable country for the source IP address

These errors should go away once you get more, properly formatted  forensic reports.

If you can provide samples you've tried, that would help confirm my theory.

**Comment by xennn** [comment]
I have not imported many forensic reports yet. That can of course be because of it.
Here is a anonymous example:

https://pastebin.com/P4Z1kLTk

**Comment by xennn** [comment]
Hey, your comment in changelog is not correct. The Dmarc Report is generated by a Symantec Mailrelay (Brightmail)

**Comment by seanthegeek** [comment]
Fixed. Thanks!

**Comment by xennn** [comment]
Hmm its not working for me. Have you a updated "kibana_saved_objects.json" ? i get the same error message.

**Comment by seanthegeek** [comment]
Hmmm. I wonder if I have to export the index patterns with them? I didn't want to do that, because that grows every time a new email header type is added.

Try it

https://gist.githubusercontent.com/seanthegeek/be15d1e8d3c84db4d0e3736cf2696f6b/raw/2d6fb8491029a0775d644c41c57ad2d489fbfb4b/kibana_saved_objects.json

**Comment by xennn** [comment]
After update the new json file it works. Thanks!

**Comment by seanthegeek** [comment]
Awesome. Thanks for all of your feedback.

**Comment by xennn** [comment]
Now a forensic dashboard would be great.With a summary of the Forensic Visualize

**Comment by seanthegeek** [comment]
I'm not sure what you mean

**Comment by xennn** [comment]
https://imgur.com/a/pqTJmg4
https://imgur.com/a/ARRfHRl

**Comment by seanthegeek** [comment]
The DMARC Forensic Samples Dashboard does that. It's included in `kibana_saved_objects.json`. It looks like you already have it imported.
