### ISSUE TITLE
After changing configuration do complete rebuild of data how?

### ISSUE THREAD

**Issue by massivedynamics1** [domainaware/parsedmarc#228]
Hello,

How do I trigger a rebuild of everything when changing parsedmarc configuration.

For example initially I had in the configuration 
[general]
offline = True

Now I would like to rebuild everything again with different configuration for example
[general]
offline = False

I have over 500 email reports on my dmarc mailbox. Do I just set them as unread and run it again?

Also I am looking for a way to do detail reports for each domain and I can't see that. Maybe it's because of using offline mode at the start.

Thank you!

**Comment by supaeasy** [comment]
Stop the container, then use 
`docker system prune -a`
You have to put the DMARC-Reports back into your inbox. Read/unread doesn't make a difference. 

As for detailed reports: Do you mean forensic reports? If yes you need to edit your DNS record and include (for all reports) fo=0:1:d:s as well as ruf=mailto:dmarcreportaddress@yourdomain.com. If you receive them on another domain make sure to verify the receiving domain with another dns entry. This is very well explained here: https://www.dmarcanalyzer.com/dmarc/dmarc-record-check/

As far as I know there is no way to receive these retospectively though.

**Comment by supaeasy** [comment]
hmm I am running a kind of different setup [with elasticsearch and Grafana](https://github.com/supaeasy/dmarc-visualizer) - But I THINK I read somewhere, that this fault is caused by a too recent Elasticsearch version because the naming of something somewhere changed either from or to using "_" at some point from one version to the other. I didn't look into it because It was not about my specific problem in the end. But maybe this gives you a hint what to look for. 
The results shown below can definitely be displayed.
