### ISSUE TITLE
No matching indices found: No indices match pattern “dmarc_aggregate*”

### ISSUE THREAD

**Issue by valleydon** [domainaware/parsedmarc#268]
Getting the error in Kibana when trying to load the info - No matching indices found: No indices match pattern “dmarc_aggregate*”

Tried the install on two fresh build Ubuntu server 20.04 with same results. Parsedmarc seems to be pulling and parsing emails fine from my mailbox.

**Comment by leonardo0014** [comment]
The Grafana resource names are _dmarc-ag_ and _dmarc-fo_. 
The specification is missing in the description of the JSON example.

**Comment by variamus** [comment]
Hello I've the same problem.
Could you please detail about how to solve this ?

**Comment by valleydon** [comment]
Just did a fresh install using the solution from variamus but still having same issue.

**Comment by seanthegeek** [comment]
Kibana will show this error until data is added in elasticsearch by parsedmarc

**Comment by cleellacer** [comment]
sorry for the noob question(s). so if I set this up but have not fed the site any reports, I should get this message?  while i figure out how to have the reports automatically retrieved, is there a way to place the GZ (or xml) files in a location on the server to be be parsed?
I'm extremely new to all of this.  but would like to try to parse these reports internally (first) before going to a third party solution to monitor these reports.

thanks in advance.

**Comment by msizec** [comment]
Hi 
I facing the same issue
No index are created in elasticsearch, only the geoip one
But my emails were parsed a while ago

**Comment by GIYItalk** [comment]
hi I wonder if there is a solution~

**Comment by Steltek** [comment]
I might be wrong, but my theory is that this is a result of parsedmarc only creating elasticsearch indexes when it tries to save report data. If there is no report to save, no index gets created, and this confuses Kibana and Grafana who expect the index to be there regardless. If correct, the fix would be to rewrite parsedmarc to create ES indexes in advance (e.g. for today and maybe tomorrow, if run daily), regardless of whether there's data to be put into them or not. (Depending on how often people run parsedmarc, this could require a "past" and "future" range parameter so that you could force it to create the next 15 days for example.)
