### ISSUE TITLE
Missing field on elasticsearch (source_base_domain.keyword and source_reverse_dns.keyword)

### ISSUE THREAD

**Issue by xseth** [domainaware/parsedmarc#271]
I can't display the information in elasticsearch dashboard with this index pattern (v 7.15.1)

source_base_domain.keyword
source_reverse_dns.keyword
This field associated with this object no longer exist in the index pattern. Please use another field.

**Comment by knightian** [comment]
Can confirm I have same error @seanthegeek

**Comment by knightian** [comment]
@xseth I solved this error. It was because parsedmarc is defaulting to DNS by Cloudflare (1.1.1.1) by default, and my environment was not allowing that. By setting to use my local DNS resolver in the `namservers=x.x.x.x` setting, this error was resolved as it began doing reverse DNS lookups and then populating the index with those fields.

Maybe this can fix for you too!

**Comment by xseth** [comment]
Thanks @knightian 
Indeed I had already put the nameserver value in my config, but without the "s" in nameserverS

**Comment by GhostRock37** [comment]
hello @xseth  @knightian  ! first: thank you for your fix !! 
where have you put the config namserver=x.x.x.x ? on the parsedmarc.ini ?

**Comment by knightian** [comment]
@GhostRock37 under [general] as per the documentation here https://domainaware.github.io/parsedmarc/

**Comment by GIYItalk** [comment]
After adding namserver=8.8.8.8 to the configuration file, the error was changed to source_base_domain.keyword, how to solve source_base_domain.keyword
