### ISSUE TITLE
IMAP Error: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by zcarmichael** [domainaware/parsedmarc#323]
I have Parsedmarc configured to use DavMail because our organization uses Exchange/OWA, not IMAP. I get this error when checking the status of parsedmarc.service in systemctl. The service will try activating, give that error, and then exit. Is there a fix for this?

**Comment by nathanthorpe** [comment]
Can you post the configuration you are using with the secrets omitted?

**Comment by zcarmichael** [comment]
Sure, sending you an image to your email.

**Comment by JP-Ellis** [comment]
I had the same issue, and the issue was due to the quotes being included in the string (this is for example a different behaviour than say TOML files).

Specifically:

| Configuration | Value |
| --- | --- |
| `host = "imap.gmail.com"` | `"imap.gmail.com"` |
| `host = imap.gmail.com` | `imap.gmail.com` |
