### ISSUE TITLE
Noticed that the docs say 2 second default timeout, actual is 6.

### ISSUE THREAD

**Issue by mikesiegel** [domainaware/parsedmarc#34]
Wasn't sure which you wanted?

https://github.com/domainaware/parsedmarc/blob/1bd6d46b61ad2e2ab13bf4ed01e99d8cf6f598f7/parsedmarc/cli.py#L105

Noticed this while troubleshooting some performance stuff. I have a 900,000 line DMARC report from Google which was taking over 24 hours and seemed mostly to be related to get_reverse_dns().

![dmarc_sanitized](https://user-images.githubusercontent.com/6181113/48627029-810d8500-e981-11e8-948b-542a8c7a09c2.png)

**Comment by seanthegeek** [comment]
This has been fixed in `parsedmarc` 5.0.0. It does DNS caching now too, so it should be much faster for large reports like that!

**Warning**: Re-importing `kibana_saved_objects.json` in Kibana [is required](https://domainaware.github.io/parsedmarc/#upgrading-kibana-index-patterns) when upgrading to this version!
