### ISSUE TITLE
Parsing Error Alerting

### ISSUE THREAD

**Issue by kklouzal** [domainaware/parsedmarc#554]
Feature request for parsing error alerts. We know the report is moved into an 'invalid' folder if a parsing error occurs. We are requesting a configuration option allowing users to specify an email address. When a report is moved to the 'invalid' folder, an email is shot off to the address specified to alert on the invalid report.

**Comment by seanthegeek** [comment]
I'm not sure what the use case is here. 

- The reports are coming from third parties, so an invalid report wouldn't necessarily mean that there is something for the user of parsedmarc to address.
- If you mean sudden errors/ regressions like what happened in #549, I have added a sample SMTP-TLS email to the test suite so that won't happen again

The best way to spot a drop in incoming valid reports is to set up an alert in whatever logging platform that parsedmarc is sending data to.
