### ISSUE TITLE
Error starting ngix serive

### ISSUE THREAD

**Issue by StarDavos** [domainaware/parsedmarc#6]
I keep getting this error when starting the ngix service
nginx: [emerg] unexpected end of file, expecting ";" or "}" in /etc/nginx/sites-enabled/kibana:33

I have checked the script and I do not see a missing ; or } - 

Your in site will be greatly appreciated -

**Comment by seanthegeek** [comment]
Can you post the content of the file so I can look over it?

**Comment by StarDavos** [comment]
The kibana file? Its the one straight from the walk through on your github page-

________________________________

**Comment by seanthegeek** [comment]
Line 33 is at the end of the file. Make sure you didn't miss the } at the end when copy pasting the example.

**Comment by StarDavos** [comment]
I was thinking that - but its not - thats why the error is so strange - Here is a screen shot of the error -


[cid:c94513bc-6b2f-46a9-bd67-3324ae75b772]


________________________________

**Comment by dneall** [comment]
I am experiencing this same issue as well. I will update if I find any additional information.

**Comment by mikeyz24** [comment]
I'm just going through the documentation and i've run into this issue also.  The problem is with the ssl_ciphers line.

`ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHAC   ssl_prefer_server_ciphers on;`

It must be a copy/paste issue.... I changed it to the following (2 lines) and removed the single quote after ssl_ciphers:
`ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHAC;`
`ssl_prefer_server_ciphers on;`

**Comment by seanthegeek** [comment]
I just fixed the example file in the documentation. Sorry about that!
